### ISSUE TITLE
[BUG] Not working on OnePlus 9 Pro

### ISSUE THREAD

**Issue by AlexV525** [ajinasokan/flutter_displaymode#10]
Just got the new OnePlus device, tested with the plugin and it seems not working well.

`matches.last` is at 120Hz refresh rate.

![image](https://user-images.githubusercontent.com/15884415/113003805-a93e5d00-91a5-11eb-82a7-8400863c250a.png)

**Comment by AlexV525** [comment]
Tracking native code, the logic seems solid but it doesn't take effects.

![image](https://user-images.githubusercontent.com/15884415/113007953-38993f80-91a9-11eb-94b9-c716ef86cbf6.png)

![image](https://user-images.githubusercontent.com/15884415/113008031-477ff200-91a9-11eb-9acf-fad2e2d21a81.png)

![image](https://user-images.githubusercontent.com/15884415/113008114-5666a480-91a9-11eb-8420-d93de02b5356.png)

**Comment by AlexV525** [comment]
Do you think whether I should reopen the closed issue in flutter repo again?

**Comment by ajinasokan** [comment]
Did you check the settings to see if there is anything that can block this? From what I read OP9 has a new mode to automatically switch to high refresh rates of its LTPO panel. 

Have a look at logcat as well while you try to switch modes.

**Comment by AlexV525** [comment]
> Did you check the settings to see if there is anything that can block this?

Checked, currently the factory mode is unable to call, the only place to control the refresh rate is here:

![Screenshot_2021-03-31-13-03-48-03](https://user-images.githubusercontent.com/15884415/113094018-8bafd880-9223-11eb-9992-0cf8fd81f6c4.jpg)

> From what I read OP9 has a new mode to automatically switch to high refresh rates of its LTPO panel.

You mean the automatically 1~120Hz mode? Yes it's enabled by default when you choose the 120Hz refresh rate.

> Have a look at logcat as well while you try to switch modes.

There are no helpful logs when toggling between modes.

**Comment by dJani97** [comment]
@AlexV525 I know it's not a proper fix, just curious: does this ADB command work for you?

`adb shell settings put global oneplus_screen_refresh_rate 0`

On previous OnePlus phones, this command disables optimization and forces the phone to use it's max refresh rate all the time. It works well with the 8T in all Flutter apps and even some games.

**Comment by AlexV525** [comment]
> @AlexV525 I know it's not a proper fix, just curious: does this ADB command work for you?

Sure, this global setting works fine in every previous OP devices, I used to use this trick on 8 Pro. But now 9/9 Pro has switched to ColorOS (maybe only in China) so the config list doesn't include the column anymore.

More further info is I tried to switch between modes in settings and see if there is a column being modified, but it didn't.

Anyway thanks for the reply, but it's failed on OP9+ColorOS.

**Comment by dJani97** [comment]
Right, I forgot about the ColorOS part.

Then I wonder if this issue with changing the display mode is specific to the OnePlus 9 Pro, or rather it's an issue with ColorOS. It would be interesting to see results from older ColorOS devices, and also the OxygenOS version of the OnePlus 9 Pro.

**Comment by AlexV525** [comment]
Yep. Since my new device will be use as a daily driver, I don't have plans to make it Oxygen currently, and I don't have any devices that can both have high refresh rate and ColorOS (my OP8 is going to be recycled).

**Comment by AlexV525** [comment]
I've opened couple threads in official forums. Let's see if any helpful response can get.

https://forums.oneplus.com/threads/bug-preferred-displaymode-settings-not-working-on-op9-coloros-11.1411296/
https://forum.xda-developers.com/t/preferred-displaymode-settings-not-working-on-op9-coloros-11.4254835/
https://www.oneplusbbs.com/forum.php?mod=viewthread&tid=5891851

**Comment by AlexV525** [comment]
Now I'm pretty sure that this is a ColorOS issue because #6 looks like the same problem. ColorOS is used both on OP9 and OPPO devices.

**Comment by AlexV525** [comment]
Good news, OP9 now supports to update the display mode manually. So I'm going to close this.

![image](https://user-images.githubusercontent.com/15884415/117236178-c88e7100-ae5a-11eb-9a2c-9cf9417127ad.png)

**Comment by jerboy** [comment]
@AlexV525 which version of colorOS has fixed this bug?My colorOS version is V11.2, still not fix.

**Comment by AlexV525** [comment]
> @AlexV525 which version of colorOS has fixed this bug?My colorOS version is V11.2, still not fix.

11_A.06
![Screenshot_2021-05-07-11-41-57-09](https://user-images.githubusercontent.com/15884415/117394729-415bfe80-af29-11eb-8424-e83bb09a2e75.jpg)
