### ISSUE TITLE
exception whit FlutterDisplayMode.setHighRefreshRate()

### ISSUE THREAD

**Issue by Maatteogekko** [ajinasokan/flutter_displaymode#12]
```dart
import 'package:flutter/material.dart';
import 'package:flutter_displaymode/flutter_displaymode.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    await FlutterDisplayMode.setHighRefreshRate();
  } catch (e) {
    print(e);
  }

  runApp(...);
}

```

Whit this I get an exception:
 `MissingPluginException(No implementation found for method getSupportedModes on channel flutter_display_mode)`

I'm testing this on a OnePlus 7T Pro running Oxygen Os 11.
Am I using this wrong?

**Comment by ajinasokan** [comment]
Are you sure you rebuilt the Android app after adding the lib? Just a hot restart will not work.

This exception is because the Java part of the plugin is not present in the app.

**Comment by Maatteogekko** [comment]
It works!
I thought I had tried to rebuild it but evidently did not.
Thanks!
