### ISSUE TITLE
Random black screens on OnePlus Nord 90hz display

### ISSUE THREAD

**Issue by RaymondBakker** [ajinasokan/flutter_displaymode#15]
Calling `FlutterDisplayMode.setHighRefreshRate();` before or right after `runApp()` causes random black screens when switching back to the app or when turning the screen off and on again (any event triggering Android's onResume) . Should this call not be placed in `main()` and in screen states instead?

Has anyone else noticed this behaviour?

![image](https://user-images.githubusercontent.com/17222640/147753985-cf2d1d73-e747-45f7-b9e5-4253a8cfa294.png)

**Comment by ajinasokan** [comment]
I have observed the black screen issue in my apps as well. But I was unable to find the root cause or reproduce it consistently. How did you figure that it was happening after `setHighRefreshRate`? Could you explain how you reproduced it? Are there any logs?

**Comment by RaymondBakker** [comment]
At least good to know I'm not the only one experiencing this. I know that setHighRefreshRate is at least causing the random black screens, because if I remove this call then black screens never occur. However, looking at the underlying code I see nothing out of the ordinary.

Thus far, I haven't been able to see anything special in logs, but now that I know I'm not the only one I'll start looking more. What I have been able to confirm is that the black screens occur in both debug and release mode.

**Comment by RaymondBakker** [comment]
Flutter logs don't seem to show anything out of the ordinary except for the unknown event types, which I think are OS issues created by OnePlus...

```
Syncing files to device ***...
D/OpScreenModeManager( 7929): setRefreshRate parent io.flutter.embedding.android.FlutterView{6fd2f0e VFE...... ........ 0,0-1080,2265 #1} parent width 1080 parent height 2265 mRatio 1.2
D/OpScreenModeManager( 7929): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{dab1109 V.E...... ........ 0,0-1080,2265} viewRate 1 width 1080 height 2265
D/DecorView( 7929): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@d411e6[MainActivity]
D/ViewRootImpl[MainActivity]( 7929): windowFocusChanged hasFocus=true inTouchMode=true
W/DisplayEventDispatcher( 7929): dispatcher 0xb400006e5f1565d0 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher( 7929): dispatcher 0xb400006eaf12aa90 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher( 7929): dispatcher 0xb400006eaf12aa90 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher( 7929): dispatcher 0xb400006e5f1565d0 ~ ignoring unknown event type 0x6d746f6e
E/sqlite3_android( 7929): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
```

**Comment by RaymondBakker** [comment]
Looks like this may be related to https://github.com/flutter/flutter/issues/93276 and https://github.com/flutter/flutter/issues/94921 instead.
