### ISSUE TITLE
About scrolling on iphone13 

### ISSUE THREAD

**Issue by isyshuai** [ajinasokan/flutter_displaymode#16]
Whether to support iphone13 to achieve 120hz 🤔

**Comment by ajinasokan** [comment]
That is being worked in the Flutter engine itself since it has official APIs in iOS. This library can only work with OLED with different preset refresh rates and not LTPO panels.

**Comment by ajinasokan** [comment]
You can track it here: https://flutter.dev/go/variable-refresh-rate

**Comment by ajinasokan** [comment]
Closing as this is fixed in Flutter 3.0. Ref: [https://github.com/flutter/flutter/issues/90675](https://github.com/flutter/flutter/issues/90675)
