### ISSUE TITLE
Motion smoothing on video

### ISSUE THREAD

**Issue by sudhanshugairola** [ajinasokan/flutter_displaymode#17]
This module perfectly work with ui but not supported 120fps or 90 hz interpolation on video with this module. 
(Video player through video_player)

**Comment by ajinasokan** [comment]
That is something out of scope of this plugin. Partially due to this plugin having no connection towards the video_player. Also motion interpolation is an extremely hard thing to do that requires special hardware or very high performance out of CPU.
