### ISSUE TITLE
 dosn't work on embedded flutter(flutter_boost).

### ISSUE THREAD

**Issue by lwj1994** [ajinasokan/flutter_displaymode#26]
app using [flutter_boost](https://github.com/alibaba/flutter_boost) as Container.

it dosn't work on flutter_boost , but success in pure flutter app on same device,

**Comment by ZhuJHua** [comment]
So how to solve it?

**Comment by lwj1994** [comment]
> So how to solve it?

Android的话，注册每个activity 的初始化，执行高刷. 他这个库默认只会对当前activity起作用，而flutteboost 或者混合项目是每个flutter 容器有单独的activity

**Comment by ZhuJHua** [comment]
> > So how to solve it?
> 
> Android的话，注册每个activity 的初始化，执行高刷. 他这个库默认只会对当前activity起作用，而flutteboost 或者混合项目是每个flutter 容器有单独的activity

谢谢，我去试一试
