### ISSUE TITLE
setPreferredMode does not do anything

### ISSUE THREAD

**Issue by 594238813** [ajinasokan/flutter_displaymode#27]
![image](https://github.com/user-attachments/assets/a62c2d43-32fa-42bf-98ca-a0cfd1336477)
![image](https://github.com/user-attachments/assets/d2a21cb2-907e-478e-a087-388b501ece8c)

always 60hz  ， I need help

xiaomi 13  
 
![35311d350f886a46e9c45a44c3388d2](https://github.com/user-attachments/assets/a1d8b32d-af30-480f-ae35-4e931136c22a)

**Comment by 594238813** [comment]
in multi-window mode， can reach 120hz

**Comment by ajinasokan** [comment]
It is up to the OS to switch to a different mode. The final control is for the OS. That is why API is named as 'setPreferredMode' instead of 'setMode'.

Have you checked if you have any battery saving settings on? What are the options in the display settings to set the refresh rate? Is it locked to 60Hz? Are you able to switch to a lower frame rate?

**Comment by 594238813** [comment]
run this demo https://github.com/syncfusion/flutter-examples   120hz ，download apk in googleplay 120hz
![d580d3d63b8a52e74b8e2af7b4180f2](https://github.com/user-attachments/assets/b5f9180c-25b3-4846-a7b7-7b234bf76143)
![ad930cf66bc2dd457f19a129205ded2](https://github.com/user-attachments/assets/d1b14590-b28e-4b51-a5e1-f7c0b173631a) 
alaws 60hz

I have updated the Flutter version  （It shouldn't be a version issue）
solved it

**Comment by rbozan** [comment]
> run this demo https://github.com/syncfusion/flutter-examples 120hz ，download apk in googleplay 120hz ![d580d3d63b8a52e74b8e2af7b4180f2](https://github.com/user-attachments/assets/b5f9180c-25b3-4846-a7b7-7b234bf76143) ![ad930cf66bc2dd457f19a129205ded2](https://github.com/user-attachments/assets/d1b14590-b28e-4b51-a5e1-f7c0b173631a) alaws 60hz
> 
> I have updated the Flutter version （It shouldn't be a version issue） solved it

So what's the solution
