### ISSUE TITLE
no working in my device

### ISSUE THREAD

**Issue by msidolphin** [ajinasokan/flutter_displaymode#6]
oppo find x2 pro
![WechatIMG1737](https://user-images.githubusercontent.com/26672484/106433895-c4ddfd80-64ab-11eb-92d1-b23ad200c29c.jpeg)

[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.14.5 18F203, locale zh-Hans-CN)
    • Flutter version 1.22.2 at /development/flutter/lib/flutter
    • Framework revision 84f3d28555 (4 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by ajinasokan** [comment]
Seems like a device specific issue. Did you check adb logs while your app is running? Usually when we switch between modes these things get logged in logcat. You might find something useful there.

**Comment by dJani97** [comment]
Hi @msidolphin!
Have you been able to solve this issue somehow? Recently a very similar problem came up with another ColorOS device, mentioned above. It would probably help the OP to know the outcome.
