### ISSUE TITLE
Separate LayoutParams.preferredDisplayModeId and Display.getMode()

### ISSUE THREAD

**Issue by ajinasokan** [ajinasokan/flutter_displaymode#9]
- `LayoutParams.preferredDisplayModeId`[1] is the id of the display mode set by the app. It can be 0 which makes it an automatic mode where system decides the mode.
- `Display.getMode()`[2] is the id of the currently active one. It can vary if preferred is automatic and system is switching between modes.

These should be distinct in the APIs and plugin should allow to reset back to automatic mode. Following breaking changes will have to be done to correct the behaviour:

- Deprecate `FlutterDisplayMode.setDefaultMode` because it is essentially setting the currently selected mode by system to be the preferred one.
- Rename `selected` field in `DisplayMode` to `active` because `selected` sounds like user selected this
- Rename `FlutterDisplayMode.current` to `FlutterDisplayMode.active` to keep it consistent above change.
- Add `FlutterDisplayMode.preferred` and `FlutterDisplayMode.setPreferred(Mode)` to get and set the preferred mode.

/cc @AlexV525 

[1] https://developer.android.com/reference/android/view/WindowManager.LayoutParams#preferredDisplayModeId
[2] https://developer.android.com/reference/android/view/Display#getMode()

**Comment by AlexV525** [comment]
SGTM. After this the package seems completely functional and solid, we can make it `1.0.0`.

On the other hand, any progress about implement this into the engine (as you mentioned before)?

**Comment by ajinasokan** [comment]
Nothing yet. Will need a lot of time to figure that out.

**Comment by AlexV525** [comment]
One more thing about the implementation. Before this package aims to solve the mode issue that flutter app refresh rate will be reduced when it's running on devices like OnePlus 7 Pro because these devices have a weird behavior with high refresh rate. How do users implement a higher refresh rate when system set to higher one but flutter got a lower one?

**Comment by ajinasokan** [comment]
High refresh rate seems to be unaffected. The behaviour I noticed was with the resolutions. When I set `#3 1440x3120 @ 90Hz` as my preferred mode it chose `#2 1080x2340 @ 90Hz` as the mode. Means it kept the refresh rate preference but switched to 1080p. This is seems due to the resolution settings I have in my phone settings. I have set it as 1080p.
